name: NETLIFY - Multi Project Pipeline

on:
  push:
    branches:
      - master

jobs:
  check_changes_01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if changes in Project_01
        id: check_project_01_changes
        run: |
          if git diff --quiet --exit-code ${{ github.event.before }} ${{ github.sha }} -- 'Project_01/'; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

  project_01:
    name: Uploading Project 01 to netlify
    runs-on: ubuntu-latest
    needs: [check_changes_01]
    if: ${{ needs.check_changes.outputs.changes == 'true' }}
    steps:
      - name: Build Project 01 - Echo
        run : echo "Building Project 01..."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing Netlify CLI
        run : npm install -g netlify-cli

      - name: Deploying to Netlify
        run : |
          netlify deploy --prod \
          --dir=. \
          --site ${{ secrets.NETLIFY_PROJECT_01_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_Project_01_02_TOKEN }}

  check_changes_02:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if changes in Project_02
        id: check_project_02_changes
        run: |
          if git diff --quiet --exit-code ${{ github.event.before }} ${{ github.sha }} -- 'Project_02/'; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

  project_02:
    name: Uploading Project 02 to netlify
    runs-on: ubuntu-latest
    needs: [check_changes_02]
    if: ${{ needs.check_changes.outputs.changes == 'true' }}
    steps:
      - name: Build Project 02 - Echo
        run : echo "Building Project 02..."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing Netlify CLI
        run : npm install -g netlify-cli

      - name: Deploying to Netlify
        run : |
          netlify deploy --prod \
          --dir=. \
          --site ${{ secrets.NETLIFY_PROJECT_02_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_Project_01_02_TOKEN }}

  no_project:
      name: Failure
      runs-on: ubuntu-latest
      steps:
        - name: Echo failure
          run : echo "Building conditions failed..."